context:
  name: dayplot
  version: "0.3.3"
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: deceb31f5d18d5fc721262198ed0b3a42594a00162039b405b1a93e44884f6b6

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base

tests:
  - python:
      imports:
        - dayplot
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://josephbarbierdarnal.github.io/dayplot/
  summary: 'Build calendar heatmaps with ease'
  description: |
    A simple-to-use Python library to build calendar heatmaps with ease.
    It's built on top of matplotlib and leverages it to access high customization possibilities.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/JosephBARBIERDARNAL/dayplot

extra:
  recipe-maintainers:
    - claudiushaag
    - JosephBARBIERDARNAL
