context:
  name: dayplot
  version: "0.5.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8506d7246572fd4fecf59a6a58c957d1d6a49b3534ddc895fe45924d3e57385d

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - matplotlib-base
    - narwhals >=1.0

tests:
  - python:
      imports:
        - dayplot
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://y-sunflower.github.io/dayplot/
  summary: 'Build calendar heatmaps with ease'
  description: |
    A simple-to-use Python library to build calendar heatmaps with ease.
    It's built on top of matplotlib and leverages it to access high customization possibilities.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/y-sunflower/dayplot
  documentation: https://y-sunflower.github.io/dayplot/reference/calendar/

extra:
  recipe-maintainers:
    - claudiushaag
    - JosephBARBIERDARNAL
